// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: autorole.sql

package sqlc

import (
	"context"
)

const createAutoRole = `-- name: CreateAutoRole :one

INSERT INTO auto_roles (guild_id, role_id, trigger)
VALUES ($1, $2, $3)
RETURNING id, guild_id, role_id, trigger
`

type CreateAutoRoleParams struct {
	GuildID string `json:"guild_id"`
	RoleID  string `json:"role_id"`
	Trigger string `json:"trigger"`
}

// AutoRoles table queries
func (q *Queries) CreateAutoRole(ctx context.Context, arg CreateAutoRoleParams) (AutoRole, error) {
	row := q.db.QueryRow(ctx, createAutoRole, arg.GuildID, arg.RoleID, arg.Trigger)
	var i AutoRole
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.RoleID,
		&i.Trigger,
	)
	return i, err
}

const createUserTrigger = `-- name: CreateUserTrigger :exec

INSERT INTO autorole_user_triggers (guild_id, user_id, trigger)
VALUES ($1, $2, $3)
ON CONFLICT (guild_id, user_id, trigger) DO NOTHING
`

type CreateUserTriggerParams struct {
	GuildID string `json:"guild_id"`
	UserID  string `json:"user_id"`
	Trigger string `json:"trigger"`
}

// AutoroleUserTriggers table queries
func (q *Queries) CreateUserTrigger(ctx context.Context, arg CreateUserTriggerParams) error {
	_, err := q.db.Exec(ctx, createUserTrigger, arg.GuildID, arg.UserID, arg.Trigger)
	return err
}

const deleteAllAutoRolesForGuild = `-- name: DeleteAllAutoRolesForGuild :exec
DELETE FROM auto_roles WHERE guild_id = $1
`

func (q *Queries) DeleteAllAutoRolesForGuild(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, deleteAllAutoRolesForGuild, guildID)
	return err
}

const deleteAutoRole = `-- name: DeleteAutoRole :exec
DELETE FROM auto_roles WHERE id = $1
`

func (q *Queries) DeleteAutoRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAutoRole, id)
	return err
}

const deleteAutoRoleByGuildAndRoleAndTrigger = `-- name: DeleteAutoRoleByGuildAndRoleAndTrigger :exec
DELETE FROM auto_roles WHERE guild_id = $1 AND role_id = $2 AND trigger = $3
`

type DeleteAutoRoleByGuildAndRoleAndTriggerParams struct {
	GuildID string `json:"guild_id"`
	RoleID  string `json:"role_id"`
	Trigger string `json:"trigger"`
}

func (q *Queries) DeleteAutoRoleByGuildAndRoleAndTrigger(ctx context.Context, arg DeleteAutoRoleByGuildAndRoleAndTriggerParams) error {
	_, err := q.db.Exec(ctx, deleteAutoRoleByGuildAndRoleAndTrigger, arg.GuildID, arg.RoleID, arg.Trigger)
	return err
}

const deleteUserTriggersForGuild = `-- name: DeleteUserTriggersForGuild :exec
DELETE FROM autorole_user_triggers WHERE guild_id = $1
`

func (q *Queries) DeleteUserTriggersForGuild(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, deleteUserTriggersForGuild, guildID)
	return err
}

const getAutoRole = `-- name: GetAutoRole :one
SELECT id, guild_id, role_id, trigger FROM auto_roles WHERE id = $1
`

func (q *Queries) GetAutoRole(ctx context.Context, id int32) (AutoRole, error) {
	row := q.db.QueryRow(ctx, getAutoRole, id)
	var i AutoRole
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.RoleID,
		&i.Trigger,
	)
	return i, err
}

const getAutoRoleByGuildAndRoleAndTrigger = `-- name: GetAutoRoleByGuildAndRoleAndTrigger :one
SELECT id, guild_id, role_id, trigger FROM auto_roles WHERE guild_id = $1 AND role_id = $2 AND trigger = $3
`

type GetAutoRoleByGuildAndRoleAndTriggerParams struct {
	GuildID string `json:"guild_id"`
	RoleID  string `json:"role_id"`
	Trigger string `json:"trigger"`
}

func (q *Queries) GetAutoRoleByGuildAndRoleAndTrigger(ctx context.Context, arg GetAutoRoleByGuildAndRoleAndTriggerParams) (AutoRole, error) {
	row := q.db.QueryRow(ctx, getAutoRoleByGuildAndRoleAndTrigger, arg.GuildID, arg.RoleID, arg.Trigger)
	var i AutoRole
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.RoleID,
		&i.Trigger,
	)
	return i, err
}

const getUserTrigger = `-- name: GetUserTrigger :one
SELECT guild_id, user_id, trigger, triggered_at FROM autorole_user_triggers WHERE guild_id = $1 AND user_id = $2 AND trigger = $3
`

type GetUserTriggerParams struct {
	GuildID string `json:"guild_id"`
	UserID  string `json:"user_id"`
	Trigger string `json:"trigger"`
}

func (q *Queries) GetUserTrigger(ctx context.Context, arg GetUserTriggerParams) (AutoroleUserTrigger, error) {
	row := q.db.QueryRow(ctx, getUserTrigger, arg.GuildID, arg.UserID, arg.Trigger)
	var i AutoroleUserTrigger
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Trigger,
		&i.TriggeredAt,
	)
	return i, err
}

const listAutoRolesByGuild = `-- name: ListAutoRolesByGuild :many
SELECT id, guild_id, role_id, trigger FROM auto_roles WHERE guild_id = $1 ORDER BY trigger, role_id
`

func (q *Queries) ListAutoRolesByGuild(ctx context.Context, guildID string) ([]AutoRole, error) {
	rows, err := q.db.Query(ctx, listAutoRolesByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutoRole{}
	for rows.Next() {
		var i AutoRole
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.RoleID,
			&i.Trigger,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoRolesByGuildAndTrigger = `-- name: ListAutoRolesByGuildAndTrigger :many
SELECT id, guild_id, role_id, trigger FROM auto_roles WHERE guild_id = $1 AND trigger = $2 ORDER BY role_id
`

type ListAutoRolesByGuildAndTriggerParams struct {
	GuildID string `json:"guild_id"`
	Trigger string `json:"trigger"`
}

func (q *Queries) ListAutoRolesByGuildAndTrigger(ctx context.Context, arg ListAutoRolesByGuildAndTriggerParams) ([]AutoRole, error) {
	rows, err := q.db.Query(ctx, listAutoRolesByGuildAndTrigger, arg.GuildID, arg.Trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutoRole{}
	for rows.Next() {
		var i AutoRole
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.RoleID,
			&i.Trigger,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
