// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jointocreate.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJTCActiveChannel = `-- name: CreateJTCActiveChannel :one
INSERT INTO jtc_active_channels (channel_id, guild_id, owner_id, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING channel_id, guild_id, owner_id, parent_id, created_at
`

type CreateJTCActiveChannelParams struct {
	ChannelID string `json:"channel_id"`
	GuildID   string `json:"guild_id"`
	OwnerID   string `json:"owner_id"`
	ParentID  string `json:"parent_id"`
}

func (q *Queries) CreateJTCActiveChannel(ctx context.Context, arg CreateJTCActiveChannelParams) (JtcActiveChannel, error) {
	row := q.db.QueryRow(ctx, createJTCActiveChannel,
		arg.ChannelID,
		arg.GuildID,
		arg.OwnerID,
		arg.ParentID,
	)
	var i JtcActiveChannel
	err := row.Scan(
		&i.ChannelID,
		&i.GuildID,
		&i.OwnerID,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const createJTCParentChannel = `-- name: CreateJTCParentChannel :one
INSERT INTO jtc_parent_channels (guild_id, channel_id, category_id, channel_name)
VALUES ($1, $2, $3, $4)
RETURNING id, guild_id, channel_id, category_id, channel_name
`

type CreateJTCParentChannelParams struct {
	GuildID     string `json:"guild_id"`
	ChannelID   string `json:"channel_id"`
	CategoryID  string `json:"category_id"`
	ChannelName string `json:"channel_name"`
}

func (q *Queries) CreateJTCParentChannel(ctx context.Context, arg CreateJTCParentChannelParams) (JtcParentChannel, error) {
	row := q.db.QueryRow(ctx, createJTCParentChannel,
		arg.GuildID,
		arg.ChannelID,
		arg.CategoryID,
		arg.ChannelName,
	)
	var i JtcParentChannel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.CategoryID,
		&i.ChannelName,
	)
	return i, err
}

const deleteJTCActiveChannel = `-- name: DeleteJTCActiveChannel :exec
DELETE FROM jtc_active_channels WHERE channel_id = $1
`

func (q *Queries) DeleteJTCActiveChannel(ctx context.Context, channelID string) error {
	_, err := q.db.Exec(ctx, deleteJTCActiveChannel, channelID)
	return err
}

const deleteJTCParentChannel = `-- name: DeleteJTCParentChannel :exec
DELETE FROM jtc_parent_channels WHERE channel_id = $1 AND guild_id = $2
`

type DeleteJTCParentChannelParams struct {
	ChannelID string `json:"channel_id"`
	GuildID   string `json:"guild_id"`
}

func (q *Queries) DeleteJTCParentChannel(ctx context.Context, arg DeleteJTCParentChannelParams) error {
	_, err := q.db.Exec(ctx, deleteJTCParentChannel, arg.ChannelID, arg.GuildID)
	return err
}

const getJTCActiveChannel = `-- name: GetJTCActiveChannel :one
SELECT channel_id, guild_id, owner_id, parent_id, created_at FROM jtc_active_channels WHERE channel_id = $1
`

func (q *Queries) GetJTCActiveChannel(ctx context.Context, channelID string) (JtcActiveChannel, error) {
	row := q.db.QueryRow(ctx, getJTCActiveChannel, channelID)
	var i JtcActiveChannel
	err := row.Scan(
		&i.ChannelID,
		&i.GuildID,
		&i.OwnerID,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const getJTCParentChannel = `-- name: GetJTCParentChannel :one
SELECT id, guild_id, channel_id, category_id, channel_name FROM jtc_parent_channels WHERE channel_id = $1
`

func (q *Queries) GetJTCParentChannel(ctx context.Context, channelID string) (JtcParentChannel, error) {
	row := q.db.QueryRow(ctx, getJTCParentChannel, channelID)
	var i JtcParentChannel
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.CategoryID,
		&i.ChannelName,
	)
	return i, err
}

const getJTCUserSettings = `-- name: GetJTCUserSettings :one
SELECT guild_id, user_id, custom_name FROM jtc_user_settings WHERE guild_id = $1 AND user_id = $2
`

type GetJTCUserSettingsParams struct {
	GuildID string `json:"guild_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetJTCUserSettings(ctx context.Context, arg GetJTCUserSettingsParams) (JtcUserSetting, error) {
	row := q.db.QueryRow(ctx, getJTCUserSettings, arg.GuildID, arg.UserID)
	var i JtcUserSetting
	err := row.Scan(&i.GuildID, &i.UserID, &i.CustomName)
	return i, err
}

const listJTCActiveChannels = `-- name: ListJTCActiveChannels :many
SELECT channel_id, guild_id, owner_id, parent_id, created_at FROM jtc_active_channels WHERE guild_id = $1
`

func (q *Queries) ListJTCActiveChannels(ctx context.Context, guildID string) ([]JtcActiveChannel, error) {
	rows, err := q.db.Query(ctx, listJTCActiveChannels, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JtcActiveChannel{}
	for rows.Next() {
		var i JtcActiveChannel
		if err := rows.Scan(
			&i.ChannelID,
			&i.GuildID,
			&i.OwnerID,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJTCParentChannels = `-- name: ListJTCParentChannels :many
SELECT id, guild_id, channel_id, category_id, channel_name FROM jtc_parent_channels WHERE guild_id = $1
`

func (q *Queries) ListJTCParentChannels(ctx context.Context, guildID string) ([]JtcParentChannel, error) {
	rows, err := q.db.Query(ctx, listJTCParentChannels, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JtcParentChannel{}
	for rows.Next() {
		var i JtcParentChannel
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.CategoryID,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countJTCParentChannels = `-- name: CountJTCParentChannels :one
SELECT COUNT(*) FROM jtc_parent_channels WHERE guild_id = $1
`

func (q *Queries) CountJTCParentChannels(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countJTCParentChannels, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listJTCParentChannelsPaginated = `-- name: ListJTCParentChannelsPaginated :many
SELECT id, guild_id, channel_id, category_id, channel_name FROM jtc_parent_channels WHERE guild_id = $1 LIMIT $2 OFFSET $3
`

func (q *Queries) ListJTCParentChannelsPaginated(ctx context.Context, guildID string, limit int32, offset int32) ([]JtcParentChannel, error) {
	rows, err := q.db.Query(ctx, listJTCParentChannelsPaginated, guildID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JtcParentChannel{}
	for rows.Next() {
		var i JtcParentChannel
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.CategoryID,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJTCUserSettings = `-- name: UpsertJTCUserSettings :exec
INSERT INTO jtc_user_settings (guild_id, user_id, custom_name)
VALUES ($1, $2, $3)
ON CONFLICT (guild_id, user_id) DO UPDATE SET custom_name = EXCLUDED.custom_name
`

type UpsertJTCUserSettingsParams struct {
	GuildID    string      `json:"guild_id"`
	UserID     string      `json:"user_id"`
	CustomName pgtype.Text `json:"custom_name"`
}

func (q *Queries) UpsertJTCUserSettings(ctx context.Context, arg UpsertJTCUserSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertJTCUserSettings, arg.GuildID, arg.UserID, arg.CustomName)
	return err
}
