// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AutoRole struct {
	ID      int32  `json:"id"`
	GuildID string `json:"guild_id"`
	RoleID  string `json:"role_id"`
	Trigger string `json:"trigger"`
}

type Guild struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GuildModule struct {
	GuildID  string          `json:"guild_id"`
	ModuleID int32           `json:"module_id"`
	Enabled  bool            `json:"enabled"`
	Config   json.RawMessage `json:"config"`
}

type JtcActiveChannel struct {
	ChannelID string             `json:"channel_id"`
	GuildID   string             `json:"guild_id"`
	OwnerID   string             `json:"owner_id"`
	ParentID  string             `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type JtcParentChannel struct {
	ID          int32  `json:"id"`
	GuildID     string `json:"guild_id"`
	ChannelID   string `json:"channel_id"`
	CategoryID  string `json:"category_id"`
	ChannelName string `json:"channel_name"`
}

type JtcUserSetting struct {
	GuildID    string      `json:"guild_id"`
	UserID     string      `json:"user_id"`
	CustomName pgtype.Text `json:"custom_name"`
}

type Module struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ReactionRole struct {
	ID        int32  `json:"id"`
	GuildID   string `json:"guild_id"`
	ChannelID string `json:"channel_id"`
	MessageID string `json:"message_id"`
	Emoji     string `json:"emoji"`
	RoleID    string `json:"role_id"`
}
