// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getGuildModule = `-- name: GetGuildModule :one
SELECT
    m.id,
    m.name,
    m.description,
    COALESCE(gm.enabled, false) AS enabled,
    COALESCE(gm.config, '{}')   AS config
FROM modules m
LEFT JOIN guild_modules gm ON gm.module_id = m.id AND gm.guild_id = $1
WHERE m.name = $2
`

type GetGuildModuleParams struct {
	GuildID string `json:"guild_id"`
	Name    string `json:"name"`
}

type GetGuildModuleRow struct {
	ID          int32           `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Enabled     bool            `json:"enabled"`
	Config      json.RawMessage `json:"config"`
}

func (q *Queries) GetGuildModule(ctx context.Context, arg GetGuildModuleParams) (GetGuildModuleRow, error) {
	row := q.db.QueryRow(ctx, getGuildModule, arg.GuildID, arg.Name)
	var i GetGuildModuleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Config,
	)
	return i, err
}

const getModuleByName = `-- name: GetModuleByName :one
SELECT id, name, description FROM modules WHERE name = $1
`

func (q *Queries) GetModuleByName(ctx context.Context, name string) (Module, error) {
	row := q.db.QueryRow(ctx, getModuleByName, name)
	var i Module
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const isModuleEnabled = `-- name: IsModuleEnabled :one
SELECT COALESCE(gm.enabled, false) AS enabled
FROM modules m
LEFT JOIN guild_modules gm ON gm.module_id = m.id AND gm.guild_id = $1
WHERE m.name = $2
`

type IsModuleEnabledParams struct {
	GuildID string `json:"guild_id"`
	Name    string `json:"name"`
}

func (q *Queries) IsModuleEnabled(ctx context.Context, arg IsModuleEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isModuleEnabled, arg.GuildID, arg.Name)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listGuildModules = `-- name: ListGuildModules :many
SELECT
    m.id,
    m.name,
    m.description,
    COALESCE(gm.enabled, false) AS enabled,
    COALESCE(gm.config, '{}')   AS config
FROM modules m
LEFT JOIN guild_modules gm ON gm.module_id = m.id AND gm.guild_id = $1
ORDER BY m.name
`

type ListGuildModulesRow struct {
	ID          int32           `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Enabled     bool            `json:"enabled"`
	Config      json.RawMessage `json:"config"`
}

func (q *Queries) ListGuildModules(ctx context.Context, guildID string) ([]ListGuildModulesRow, error) {
	rows, err := q.db.Query(ctx, listGuildModules, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildModulesRow{}
	for rows.Next() {
		var i ListGuildModulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT id, name, description FROM modules ORDER BY name
`

func (q *Queries) ListModules(ctx context.Context) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuildModule = `-- name: UpsertGuildModule :exec
INSERT INTO guild_modules (guild_id, module_id, enabled, config)
VALUES ($1, $2, $3, $4)
ON CONFLICT (guild_id, module_id) DO UPDATE
    SET enabled = EXCLUDED.enabled,
        config  = EXCLUDED.config
`

type UpsertGuildModuleParams struct {
	GuildID  string          `json:"guild_id"`
	ModuleID int32           `json:"module_id"`
	Enabled  bool            `json:"enabled"`
	Config   json.RawMessage `json:"config"`
}

func (q *Queries) UpsertGuildModule(ctx context.Context, arg UpsertGuildModuleParams) error {
	_, err := q.db.Exec(ctx, upsertGuildModule,
		arg.GuildID,
		arg.ModuleID,
		arg.Enabled,
		arg.Config,
	)
	return err
}
