// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactionroles.sql

package sqlc

import (
	"context"
)

const createReactionRole = `-- name: CreateReactionRole :one
INSERT INTO reaction_roles (guild_id, channel_id, message_id, emoji, role_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, guild_id, channel_id, message_id, emoji, role_id
`

type CreateReactionRoleParams struct {
	GuildID   string `json:"guild_id"`
	ChannelID string `json:"channel_id"`
	MessageID string `json:"message_id"`
	Emoji     string `json:"emoji"`
	RoleID    string `json:"role_id"`
}

func (q *Queries) CreateReactionRole(ctx context.Context, arg CreateReactionRoleParams) (ReactionRole, error) {
	row := q.db.QueryRow(ctx, createReactionRole,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.Emoji,
		arg.RoleID,
	)
	var i ReactionRole
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Emoji,
		&i.RoleID,
	)
	return i, err
}

const deleteAllReactionRolesForGuild = `-- name: DeleteAllReactionRolesForGuild :exec
DELETE FROM reaction_roles WHERE guild_id = $1
`

func (q *Queries) DeleteAllReactionRolesForGuild(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, deleteAllReactionRolesForGuild, guildID)
	return err
}

const deleteAllReactionRolesForMessage = `-- name: DeleteAllReactionRolesForMessage :exec
DELETE FROM reaction_roles WHERE message_id = $1
`

func (q *Queries) DeleteAllReactionRolesForMessage(ctx context.Context, messageID string) error {
	_, err := q.db.Exec(ctx, deleteAllReactionRolesForMessage, messageID)
	return err
}

const deleteReactionRole = `-- name: DeleteReactionRole :exec
DELETE FROM reaction_roles WHERE id = $1
`

func (q *Queries) DeleteReactionRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteReactionRole, id)
	return err
}

const deleteReactionRoleByMessageAndEmoji = `-- name: DeleteReactionRoleByMessageAndEmoji :exec
DELETE FROM reaction_roles WHERE message_id = $1 AND emoji = $2
`

type DeleteReactionRoleByMessageAndEmojiParams struct {
	MessageID string `json:"message_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) DeleteReactionRoleByMessageAndEmoji(ctx context.Context, arg DeleteReactionRoleByMessageAndEmojiParams) error {
	_, err := q.db.Exec(ctx, deleteReactionRoleByMessageAndEmoji, arg.MessageID, arg.Emoji)
	return err
}

const getReactionRole = `-- name: GetReactionRole :one
SELECT id, guild_id, channel_id, message_id, emoji, role_id FROM reaction_roles WHERE id = $1
`

func (q *Queries) GetReactionRole(ctx context.Context, id int32) (ReactionRole, error) {
	row := q.db.QueryRow(ctx, getReactionRole, id)
	var i ReactionRole
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Emoji,
		&i.RoleID,
	)
	return i, err
}

const getReactionRoleByMessageAndEmoji = `-- name: GetReactionRoleByMessageAndEmoji :one
SELECT id, guild_id, channel_id, message_id, emoji, role_id FROM reaction_roles WHERE message_id = $1 AND emoji = $2
`

type GetReactionRoleByMessageAndEmojiParams struct {
	MessageID string `json:"message_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) GetReactionRoleByMessageAndEmoji(ctx context.Context, arg GetReactionRoleByMessageAndEmojiParams) (ReactionRole, error) {
	row := q.db.QueryRow(ctx, getReactionRoleByMessageAndEmoji, arg.MessageID, arg.Emoji)
	var i ReactionRole
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Emoji,
		&i.RoleID,
	)
	return i, err
}

const listReactionRolesByGuild = `-- name: ListReactionRolesByGuild :many
SELECT id, guild_id, channel_id, message_id, emoji, role_id FROM reaction_roles 
WHERE guild_id = $1 
ORDER BY channel_id, message_id
`

func (q *Queries) ListReactionRolesByGuild(ctx context.Context, guildID string) ([]ReactionRole, error) {
	rows, err := q.db.Query(ctx, listReactionRolesByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionRole{}
	for rows.Next() {
		var i ReactionRole
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.Emoji,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countReactionRolesByGuild = `-- name: CountReactionRolesByGuild :one
SELECT COUNT(*) FROM reaction_roles WHERE guild_id = $1
`

func (q *Queries) CountReactionRolesByGuild(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countReactionRolesByGuild, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listReactionRolesByGuildPaginated = `-- name: ListReactionRolesByGuildPaginated :many
SELECT id, guild_id, channel_id, message_id, emoji, role_id FROM reaction_roles 
WHERE guild_id = $1 
ORDER BY channel_id, message_id LIMIT $2 OFFSET $3
`

func (q *Queries) ListReactionRolesByGuildPaginated(ctx context.Context, guildID string, limit int32, offset int32) ([]ReactionRole, error) {
	rows, err := q.db.Query(ctx, listReactionRolesByGuildPaginated, guildID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionRole{}
	for rows.Next() {
		var i ReactionRole
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.Emoji,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionRolesByMessage = `-- name: ListReactionRolesByMessage :many
SELECT id, guild_id, channel_id, message_id, emoji, role_id FROM reaction_roles WHERE message_id = $1
`

func (q *Queries) ListReactionRolesByMessage(ctx context.Context, messageID string) ([]ReactionRole, error) {
	rows, err := q.db.Query(ctx, listReactionRolesByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionRole{}
	for rows.Next() {
		var i ReactionRole
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.Emoji,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
